[project]
name = "python-llm-learning"
version = "0.1.0"
description = "Daily learning and practice of Python with a focus on LLMs (Large Language Models)."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.14",
    "httpx>=0.28.1",
    "uvicorn>=0.34.3",
]
